--- #YAML:1.0
name: accessors
version: 1.00
author:
  - Steve Purkis <spurkis@cpan.org>
abstract: create accessor methods in caller's package.
license: perl
requires:
  perl: 5.6.0
build_requires:
  Module::Build: 0.20
  Test::More: 0.01
provides:
  accessors:
    file: lib/accessors.pm
    version: 1.00
  accessors::chained:
    file: lib/accessors/chained.pm
    version: 1.00
  accessors::classic:
    file: lib/accessors/classic.pm
    version: 1.00
  accessors::ro:
    file: lib/accessors/ro.pm
    version: 1.00
  accessors::rw:
    file: lib/accessors/rw.pm
    version: 1.00
generated_by: Module::Build version 0.25
